#!/bin/bash

#Colours
greenColour="\e[0;32m\033[1m"
endColour="\033[0m\e[0m"
redColour="\e[0;31m\033[1m"
blueColour="\e[0;34m\033[1m"
yellowColour="\e[0;33m\033[1m"
purpleColour="\e[0;35m\033[1m"
turquoiseColour="\e[0;36m\033[1m"
grayColour="\e[0;37m\033[1m"

clear

function ctrl_c (){
  echo -e "\n\n${redColour}[!] Saliendo...${endColour}"
  tput cnorm && exit 1
}


# Control C
trap ctrl_c INT

tput civis

  echo -e "\n${yellowColour}¡¡¡ Indicar DNI sin 0 delante !!!${endColour}${grayColour} ejemplo:${endColour}${redColour} 01234567${endColour}${grayColour} ->${endColour}${greenColour} 1234567${endColour}"
  
  echo -e "\n${yellowColour}**${endColour}${redColour} Para salir del script pulse CONTROL_C ${endColour}${yellowColour}**${endColour}"
  
while true ; do
  echo -ne "\n${yellowColour}[+]${endColour}${greenColour} A continuación indique el número de DNI --->${endColour} "${blueColour} && read numero
 letra="$(($numero % 23))"


  if [ "$letra" -eq 0 ]; then
   letra="T"
    elif [ "$letra" -eq 1 ]; then
     letra="R"
    elif [ "$letra" -eq 2 ]; then
     letra="W"
    elif [ "$letra" -eq 3 ]; then
     letra="A"
    elif [ "$letra" -eq 4 ]; then
     letra="G"
    elif [ "$letra" -eq 5 ]; then
     letra="M"
    elif [ "$letra" -eq 6 ]; then
     letra="Y"
    elif [ "$letra" -eq 7 ]; then
     letra="F"
    elif [ "$letra" -eq 8 ]; then
     letra="P"
    elif [ "$letra" -eq 9 ]; then
     letra="D"
    elif [ "$letra" -eq 10 ]; then
     letra="X"
    elif [ "$letra" -eq 11 ]; then
     letra="B"
    elif [ "$letra" -eq 12 ]; then
     letra="N"
    elif [ "$letra" -eq 13 ]; then
     letra="J"
    elif [ "$letra" -eq 14 ]; then
     letra="Z"
    elif [ "$letra" -eq 15 ]; then
     letra="S"
    elif [ "$letra" -eq 16 ]; then
     letra="Q"
    elif [ "$letra" -eq 17 ]; then
     letra="V"
    elif [ "$letra" -eq 18 ]; then
     letra="H"
    elif [ "$letra" -eq 19 ]; then
     letra="L"
    elif [ "$letra" -eq 20 ]; then
     letra="C"
    elif [ "$letra" -eq 21 ]; then
     letra="K"
    elif [ "$letra" -eq 22 ]; then
     letra="E"
  fi

  echo -e "\n${yellowColour}[+]${endColour}${greenColour} Al dni con número${endColour}${blueColour} $numero${endColour}${greenColour} le corresponde la letra${endColour}${blueColour} $letra${endColour}"
  echo -e "\n${yellowColour}[+]${endColour}${grayColour} El número completo es -->${endColour}${purpleColour} $numero-$letra${endColour}"
done
 tput cnorm






